try:
 i = 1
 i.append(2),
except:
  print("Bu AttributeError")

# Errorni ko'rmoqchi bolsangiz try va exceptni o'chiring !